[package]
authors = ["cowboy"]
name = "rustycraft"
version = "0.0.1"
edition = "2018"

[dependencies]
bevy = "0.4.0"
bevy_prototype_lyon = "0.2"
# anyhow = "1.0"
# rand = "0.7.3"
# ron = "0.6.2"
# serde = {version = "1", features = ["derive"]}
