[package]
authors = ["cowboy"]
name = "rustycraft"
version = "0.0.1"
edition = "2018"

[dependencies]
bevy = "0.5.0"
bevy_mod_picking = "0.4.0"
bevy_flycam = { git = "https://github.com/sburris0/bevy_flycam" }
